a = int(input("Masukan nilai suku pertama :"))
n = int(input("Masukan suku yang dicari :"))
r = int(input("Masukan rasio :"))
sn = a*(r**n-1)/(r-1)
print("Hasil jumlah suku ke-11 dari deret 1,3,9,27,81,... adalah", sn)